[package]
name = "leapotron"
version = "0.1.0"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[dependencies]
egui = "0.18.0"
eframe = { version = "0.18.0" }
tracing-subscriber = "0.3"
