[package]
name = "theremotion"
version = "0.1.17"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[features]
default = ["gemini", "default-boxed"]
gemini = ["leaprs/gemini"]
default-boxed = []

[dependencies]
egui = "0.19"
eframe = { version = "0.19" }
tracing-subscriber = "0.3"
cpal = "0.14"
faust-types = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
faust-state = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
leaprs = { version = "0.1", default-features = false }
crossbeam-channel = "0.5"
nalgebra = "0.31"
staff = { git = "https://github.com/matthunz/staff", branch="main", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4", features = ["derive", "env"] }
default-boxed = "0.2"
strum = { version = "0.24", features = ["strum_macros", "derive"] }
windows = { version = "0.43.0", features = ["Win32_System_Threading", "Win32_Foundation"] }

[dev-dependencies]
rstest = "0.15"

[build-dependencies]
faust-build = { git = "https://github.com/plule/rust-faust", branch="default_boxed" }
