[workspace]
members = ["theremotion", "theremotion-dsp", "theremotion-ui"]
resolver = "2"

[profile.dev.package.theremotion-ui]
# Generated code, and tends to overflow
opt-level = 3

[profile.dev.package.theremotion-dsp]
opt-level = 3
