[package]
name = "leapotron"
version = "0.1.0"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[dependencies]
egui = "0.18.0"
eframe = { version = "0.18.0" }
tracing-subscriber = "0.3"
cpal = "0.13.5"
faust-types = { git = "https://github.com/Frando/rust-faust" }
faust-state = { git = "https://github.com/Frando/rust-faust" }
leaprs = "0.0.3"
music-note = "0.3.0"

[build-dependencies]
faust-build = { git = "https://github.com/Frando/rust-faust" }

# https://github.com/grame-cncm/faust/issues/432
[profile.dev]
overflow-checks = false
