[package]
name = "leapotron"
version = "0.1.4"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[features]
default = ["gemini"]
gemini = ["leaprs/gemini"]

[dependencies]
egui = "0.18.0"
eframe = { version = "0.18.0" }
tracing-subscriber = "0.3"
cpal = "0.13.5"
faust-types = { git = "https://github.com/Frando/rust-faust", branch="main" }
faust-state = { git = "https://github.com/Frando/rust-faust", branch="main" }
leaprs = { version = "0.0.8", default-features = false }
crossbeam-channel = "0.5.6"
nalgebra = "0.31.1"
staff = { git = "https://github.com/matthunz/staff", branch="main", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

[build-dependencies]
faust-build = { git = "https://github.com/Frando/rust-faust", branch="main" }

# https://github.com/grame-cncm/faust/issues/432
[profile.dev]
overflow-checks = false
