[package]
name = "theremotion"
version = "1.0.2-dev"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[features]
default = ["default-boxed", "leap"]
leap = ["leaprs"]
default-boxed = []

[dependencies]
egui = "0.19"
eframe = { version = "0.19" }
tracing-subscriber = "0.3"
cpal = "0.14"
faust-types = { git = "https://github.com/Frando/rust-faust", branch="main" }
faust-state = { git = "https://github.com/Frando/rust-faust", branch="main" }
leaprs = { version = "0.1", default-features = false, optional = true }
crossbeam-channel = "0.5"
nalgebra = "0.31"
staff = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4", features = ["derive", "env"] }
default-boxed = "0.2"
strum = { version = "0.24", features = ["strum_macros", "derive"] }
windows = { version = "0.43.0", features = ["Win32_System_Threading", "Win32_Foundation"] }
directories = "4.0.1"
anyhow = "1"
log = "0.4"

[dev-dependencies]
rstest = "0.15"

[build-dependencies]
faust-build = { git = "https://github.com/Frando/rust-faust", branch="main" }
