[package]
name = "leapotron"
version = "0.1.4-dev"
authors = ["Pierre Lulé <pierre@lule.fr>"]
edition = "2021"
rust-version = "1.60"

[features]
default = ["gemini"]
gemini = ["leaprs/gemini"]

[dependencies]
egui = "0.18.0"
eframe = { version = "0.18.0" }
tracing-subscriber = "0.3"
cpal = "0.13.5"
faust-types = { git = "https://github.com/plule/rust-faust", branch="contrib" }
faust-state = { git = "https://github.com/plule/rust-faust", branch="contrib" }
leaprs = { version = "0.0.7", default-features = false }
music-note = "0.3.0"
crossbeam-channel = "0.5.6"
nalgebra = "0.31.1"

[build-dependencies]
faust-build = { git = "https://github.com/plule/rust-faust", branch="contrib" }

# https://github.com/grame-cncm/faust/issues/432
[profile.dev]
overflow-checks = false
